name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build CGMiner
      run: |
        ./autogen.sh
        ./configure --enable-icarus --enable-bflsc --enable-include --enable-scrypt
        make
        make check
        make distcheck

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cgminer-binaries
        path: ./cgminer  # Adjust this path if necessary
