name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          git \
          libusb-1.0-0-dev \
          libcurl4-openssl-dev \
          libjansson-dev \
          libssl-dev

    - name: Build CGMiner
      run: |
        ./autogen.sh
        ./configure --enable-icarus --enable-bflsc --enable-include --enable-scrypt
        make
        make check
        make distcheck

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cgminer-binaries
        path: ./cgminer  # Adjust this path if necessary
